title: "뉴스 블로그"
description: "IT, 게임, PC 하드웨어 정보"
baseurl: "/jypcomputer"
url: "https://jypm.github.io"
encoding: "utf-8"

# 빌드 에러를 일으키는 불필요한 루트 파일/폴더 제외
exclude:
  - posts
  - design.md
  - diablo2-runes.md
  - game.md
  - hardware.md

# 지킬(Jekyll) 기본 설정
markdown: kramdown
permalink: /:year/:month/:day/:title/
