title: "뉴스 블로그"
description: "IT, 게임, PC 하드웨어 정보"
baseurl: "/jypcomputer"
url: "https://jypm.github.io"
encoding: "utf-8"

# 옛날 무효 폴더 및 불필요한 파일만 제외
exclude:
  - posts
  - diablo2-runes.md

# 지킬(Jekyll) 기본 설정
markdown: kramdown
permalink: /:year/:month/:day/:title/
